## NumPy Array İşlemleri

---

* NumPy kütüphanesinin içeri aktarıyoruz

In [1]:
import numpy as np

* **mylist** isminde bir liste oluşturuyoruz

In [2]:
mylist=[1,2,3]

* Oluşturduğumuz değişkenin type kontrol ediyoruz

In [3]:
type(mylist)

list

* Listemizi array'e dönüştürüyoruz. Bunu da **myarray** isimli değişkene aktarıyoruz

In [4]:
myarray=np.array(mylist)

In [5]:
myarray

array([1, 2, 3])

In [6]:
type(myarray)

numpy.ndarray

* **arange** fonksiyonunu kullanarak 0-10 arasındaki rakamlardan oluşan bir array oluşturuyoruz

In [7]:
np.arange(0,10) #shift tab yaparak fonksiyonun içeriğine bakabiliriz.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

* Çok boyutlu array oluşturulması ve arrayin elemanlarının 0 değerinden oluşmasını istiyoruz

In [9]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

* Yukarıda gözüktüğü gibi değerimiz float çünkü shift tab yaparak görebileceğimiz gibi default olarak float değeri veriyor bize. **arange** integer bir değer döndürüyor bize ama **zeros** bize float değer döndürmektedir.

In [11]:
type(0)

int

In [12]:
type(0.)

float

In [13]:
np.ones(shape=(2,4)) #shape yazmasakta aynı sonucu elde edebiliriz

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* 0-100 arasında rastgele 10 adet int değer üretiyoruz

In [15]:
random = np.random.randint(0,100,10)

In [16]:
random

array([60,  6, 96, 58, 43, 85, 17, 50, 47, 75])

In [17]:
random2 = np.random.randint(0,100,10)

In [25]:
random2

array([73, 58, 30, 67, 27,  3, 94, 40, 83, 19])

* Arrayimiz içerisinde ki en yüksek değeri bulmak için **max** fonksiyonunu kullanabilriz

In [18]:
random.max()

96

In [19]:
random2.max()

97

* Max değerimizin kaçıncı satırda olduğunu öğrenmek istiyoruz

In [20]:
random.argmax()

2

In [21]:
random2.argmax()

2

* Aynı şekilde min değerimizide aşağıdaki fonksiyonu kullanarak bulabiliriz

In [22]:
random.min()

6

In [23]:
random.argmin()

1

* Arrayin ortalamasını veren fonksiyon

In [24]:
random.mean()

53.7

In [25]:
random.shape

(10,)

* Arrayin shape'ini tekrar düzenleyebilriz

In [26]:
random.reshape((2,5))

array([[60,  6, 96, 58, 43],
       [85, 17, 50, 47, 75]])

* Indexing
* Shape ve arange belirleyerek aşağıdaki gibi bir vektör çıktısını alabiliriz

In [27]:
mat = np.arange(0,100).reshape(10,10)

In [28]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
mat.shape

(10, 10)

**Index işlemlerinin gerçekleştirilmesi**

In [30]:
row = 0
col = 2

In [31]:
mat[row,col]

2

In [32]:
mat[3,7]

37

In [33]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [35]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [36]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
mat[0:2,0:2]

array([[ 0,  1],
       [10, 11]])

In [38]:
mat[0:2,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [39]:
mat[0:2,0:4].shape

(2, 4)

In [40]:
mat[0:2,0:4] = 0

In [41]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
copy = mat.copy()

In [43]:
copy

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
copy[0:5,:] = 100

In [45]:
copy

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])